### ISSUE TITLE
Initial scaffolding of the project

### ISSUE THREAD

**Issue by jorgeimo** [christiancajiao/calculator-#2]
# Description
Use npm to initialize a new project, setup react and have an initial simple component to show that everything is working as expected:

## Constraints
- Do NOT use create-react-app.

## Useful links
- [Add React to a website](https://reactjs.org/docs/add-react-to-a-website.html)
- [How to start a Node project](https://philna.sh/blog/2019/01/10/how-to-start-a-node-js-project/)

**Comment by christiancajiao** [comment]
solved by #3
